# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API

    The version of the OpenAPI document: 6.1.24
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_iii_client.models.bill_repeat_frequency import BillRepeatFrequency

class TestBillRepeatFrequency(unittest.TestCase):
    """BillRepeatFrequency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillRepeatFrequency(self):
        """Test BillRepeatFrequency"""
        # inst = BillRepeatFrequency()

if __name__ == '__main__':
    unittest.main()
