# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API

    The version of the OpenAPI document: v6.2.10
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_iii_client.api.charts_api import ChartsApi


class TestChartsApi(unittest.TestCase):
    """ChartsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChartsApi()

    def tearDown(self) -> None:
        pass

    def test_get_chart_account_overview(self) -> None:
        """Test case for get_chart_account_overview

        Dashboard chart with asset account balance information.
        """
        pass


if __name__ == '__main__':
    unittest.main()
