# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API  # noqa: E501

    OpenAPI spec version: 0.9.0
    Contact: thegrumpydictator@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import firefly_iii_client
from firefly_iii_client.api.accounts_api import AccountsApi  # noqa: E501
from firefly_iii_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = firefly_iii_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_account(self):
        """Test case for delete_account

        Permanently delete account.  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Get single account.  # noqa: E501
        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        List all accounts.  # noqa: E501
        """
        pass

    def test_get_piggies_by_account(self):
        """Test case for get_piggies_by_account

        List all piggy banks related to the account.  # noqa: E501
        """
        pass

    def test_get_transactions_by_account(self):
        """Test case for get_transactions_by_account

        List all transactions related to the account.  # noqa: E501
        """
        pass

    def test_store_account(self):
        """Test case for store_account

        Create new account.  # noqa: E501
        """
        pass

    def test_update_account(self):
        """Test case for update_account

        Update existing account.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
