# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API

    The version of the OpenAPI document: v6.2.10
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_iii_client.models.rule_action_update import RuleActionUpdate

class TestRuleActionUpdate(unittest.TestCase):
    """RuleActionUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuleActionUpdate:
        """Test RuleActionUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuleActionUpdate`
        """
        model = RuleActionUpdate()
        if include_optional:
            return RuleActionUpdate(
                active = True,
                order = 5,
                stop_processing = False,
                type = 'set_category',
                value = 'Daily groceries'
            )
        else:
            return RuleActionUpdate(
        )
        """

    def testRuleActionUpdate(self):
        """Test RuleActionUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
