# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API

    The version of the OpenAPI document: 2.0.12
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_iii_client.models.short_account_type_property import ShortAccountTypeProperty

class TestShortAccountTypeProperty(unittest.TestCase):
    """ShortAccountTypeProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShortAccountTypeProperty(self):
        """Test ShortAccountTypeProperty"""
        # inst = ShortAccountTypeProperty()

if __name__ == '__main__':
    unittest.main()
