# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import firefly_iii_client
from firefly_iii_client.models.chart_data_point import ChartDataPoint  # noqa: E501
from firefly_iii_client.rest import ApiException


class TestChartDataPoint(unittest.TestCase):
    """ChartDataPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChartDataPoint(self):
        """Test ChartDataPoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = firefly_iii_client.models.chart_data_point.ChartDataPoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
