# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API

    The version of the OpenAPI document: 2.0.12
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_iii_client.models.export_file_filter import ExportFileFilter

class TestExportFileFilter(unittest.TestCase):
    """ExportFileFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportFileFilter(self):
        """Test ExportFileFilter"""
        # inst = ExportFileFilter()

if __name__ == '__main__':
    unittest.main()
