# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API

    The version of the OpenAPI document: v6.2.10
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_iii_client.models.user_group_read import UserGroupRead

class TestUserGroupRead(unittest.TestCase):
    """UserGroupRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserGroupRead:
        """Test UserGroupRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserGroupRead`
        """
        model = UserGroupRead()
        if include_optional:
            return UserGroupRead(
                attributes = firefly_iii_client.models.user_group_read_attributes.UserGroupReadAttributes(
                    can_see_members = True, 
                    created_at = '2018-09-17T12:46:47+01:00', 
                    in_use = False, 
                    members = [
                        firefly_iii_client.models.user_group_read_members.UserGroupReadMembers(
                            roles = [
                                'owner'
                                ], 
                            user_email = 'james@firefly-iii.org', 
                            user_id = '5', 
                            you = False, )
                        ], 
                    native_currency_code = 'EUR', 
                    native_currency_decimal_places = 2, 
                    native_currency_id = '12', 
                    native_currency_symbol = '$', 
                    title = 'demo@firefly', 
                    updated_at = '2018-09-17T12:46:47+01:00', ),
                id = '2',
                links = firefly_iii_client.models.object_link.ObjectLink(
                    0 = firefly_iii_client.models.object_link_0.ObjectLink_0(
                        rel = 'self', 
                        uri = '/OBJECTS/1', ), 
                    self = 'https://demo.firefly-iii.org/api/v1/OBJECTS/1', ),
                type = 'user_groups'
            )
        else:
            return UserGroupRead(
                attributes = firefly_iii_client.models.user_group_read_attributes.UserGroupReadAttributes(
                    can_see_members = True, 
                    created_at = '2018-09-17T12:46:47+01:00', 
                    in_use = False, 
                    members = [
                        firefly_iii_client.models.user_group_read_members.UserGroupReadMembers(
                            roles = [
                                'owner'
                                ], 
                            user_email = 'james@firefly-iii.org', 
                            user_id = '5', 
                            you = False, )
                        ], 
                    native_currency_code = 'EUR', 
                    native_currency_decimal_places = 2, 
                    native_currency_id = '12', 
                    native_currency_symbol = '$', 
                    title = 'demo@firefly', 
                    updated_at = '2018-09-17T12:46:47+01:00', ),
                id = '2',
                links = firefly_iii_client.models.object_link.ObjectLink(
                    0 = firefly_iii_client.models.object_link_0.ObjectLink_0(
                        rel = 'self', 
                        uri = '/OBJECTS/1', ), 
                    self = 'https://demo.firefly-iii.org/api/v1/OBJECTS/1', ),
                type = 'user_groups',
        )
        """

    def testUserGroupRead(self):
        """Test UserGroupRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
