# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API

    The version of the OpenAPI document: v6.2.10
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firefly_iii_client.models.object_group_read import ObjectGroupRead

class TestObjectGroupRead(unittest.TestCase):
    """ObjectGroupRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectGroupRead:
        """Test ObjectGroupRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectGroupRead`
        """
        model = ObjectGroupRead()
        if include_optional:
            return ObjectGroupRead(
                attributes = firefly_iii_client.models.object_group.ObjectGroup(
                    created_at = '2018-09-17T12:46:47+01:00', 
                    order = 1, 
                    title = 'My object group', 
                    updated_at = '2018-09-17T12:46:47+01:00', ),
                id = '2',
                type = 'object_groups'
            )
        else:
            return ObjectGroupRead(
                attributes = firefly_iii_client.models.object_group.ObjectGroup(
                    created_at = '2018-09-17T12:46:47+01:00', 
                    order = 1, 
                    title = 'My object group', 
                    updated_at = '2018-09-17T12:46:47+01:00', ),
                id = '2',
                type = 'object_groups',
        )
        """

    def testObjectGroupRead(self):
        """Test ObjectGroupRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
