# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API  # noqa: E501

    The version of the OpenAPI document: 2.0.5
    Contact: james@firefly-iii.org
    Generated by: https://openapi-generator.tech
"""

import unittest

import firefly_iii_client
from firefly_iii_client.model.rule_trigger_type import RuleTriggerType
from firefly_iii_client import configuration


class TestRuleTriggerType(unittest.TestCase):
    """RuleTriggerType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
