# coding: utf-8

"""
    Firefly III API Client

    This is the Python client for Firefly III API  # noqa: E501

    The version of the OpenAPI document: 0.10.0
    Contact: thegrumpydictator@gmail.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RuleTriggerUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'active': 'bool',
        'stop_processing': 'bool',
        'type': 'str',
        'value': 'str'
    }

    attribute_map = {
        'active': 'active',
        'stop_processing': 'stop_processing',
        'type': 'type',
        'value': 'value'
    }

    def __init__(self, active=None, stop_processing=None, type=None, value=None):  # noqa: E501
        """RuleTriggerUpdate - a model defined in OpenAPI"""  # noqa: E501

        self._active = None
        self._stop_processing = None
        self._type = None
        self._value = None
        self.discriminator = None

        if active is not None:
            self.active = active
        if stop_processing is not None:
            self.stop_processing = stop_processing
        self.type = type
        self.value = value

    @property
    def active(self):
        """Gets the active of this RuleTriggerUpdate.  # noqa: E501

        If the trigger is active.  # noqa: E501

        :return: The active of this RuleTriggerUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this RuleTriggerUpdate.

        If the trigger is active.  # noqa: E501

        :param active: The active of this RuleTriggerUpdate.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def stop_processing(self):
        """Gets the stop_processing of this RuleTriggerUpdate.  # noqa: E501

        When true, other triggers will not be checked if this trigger was triggered.  # noqa: E501

        :return: The stop_processing of this RuleTriggerUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._stop_processing

    @stop_processing.setter
    def stop_processing(self, stop_processing):
        """Sets the stop_processing of this RuleTriggerUpdate.

        When true, other triggers will not be checked if this trigger was triggered.  # noqa: E501

        :param stop_processing: The stop_processing of this RuleTriggerUpdate.  # noqa: E501
        :type: bool
        """

        self._stop_processing = stop_processing

    @property
    def type(self):
        """Gets the type of this RuleTriggerUpdate.  # noqa: E501

        The type of thing this trigger responds to. A limited set is possible  # noqa: E501

        :return: The type of this RuleTriggerUpdate.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RuleTriggerUpdate.

        The type of thing this trigger responds to. A limited set is possible  # noqa: E501

        :param type: The type of this RuleTriggerUpdate.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["user_action", "from_account_starts", "from_account_ends", "from_account_is", "from_account_contains", "to_account_starts", "to_account_ends", "to_account_is", "to_account_contains", "amount_less", "amount_exactly", "amount_more", "description_starts", "description_ends", "description_contains", "description_is", "transaction_type", "category_is", "budget_is", "tag_is", "currency_is", "has_attachments", "has_no_category", "has_any_category", "has_no_budget", "has_any_budget", "has_no_tag", "has_any_tag", "notes_contain", "notes_start", "notes_end", "notes_are", "no_notes", "any_notes"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def value(self):
        """Gets the value of this RuleTriggerUpdate.  # noqa: E501

        The accompanying value the trigger responds to. This value is often mandatory, but this depends on the trigger.  # noqa: E501

        :return: The value of this RuleTriggerUpdate.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RuleTriggerUpdate.

        The accompanying value the trigger responds to. This value is often mandatory, but this depends on the trigger.  # noqa: E501

        :param value: The value of this RuleTriggerUpdate.  # noqa: E501
        :type: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RuleTriggerUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
